env:
    browser: true
    es2021: true
extends:
    - eslint:recommended
    - plugin:react/recommended
    # eslint-plugin-reactを入れないとダメかも
    # eslint conf prittierを入れないとだめかも
    - prettier
parserOptions:
    ecmaVersion: latest
    sourceType: module
ignorePatterns:
    - '**/*.css'
plugins:
    - react
rules: { 'react/prop-types': 'off' }
