printWidth: 120 # 折り返し120文字以上で改行
useTabs: true # タブを使う
trailingComma: 'es5' # 末尾のカンマ
tabWidth: 4 # タブの幅
semi: false # エラーにならない箇所にはセミコロンをつけない
singleQuote: true # シングルクォートを使う
jsxSingleQuote: true # JSXでもシングルクォートを使う
proseWrap: 'never' # マークダウンでprintWidthを超えても折り返さない
